### ISSUE TITLE
The `punycode` module is deprecated.

### ISSUE THREAD

**Issue by peterwangfeng** [jsdom/tr46#41]
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead
please use punycode.js

**Comment by Hoshimikan6490** [comment]
I think so too!

**Comment by Hoshimikan6490** [comment]
My discord bot no longer works due to this package. I'm using mongodb as my database, and this package seems to be used to connect to it. So, I want you to fix this issue quickly.

Can you do this? @domenic (I mentioned you because I think you are admin in this package. If you cannot do it, I apologize for sending you the notification.)

**Comment by domenic** [comment]
This package is a spare-time project. It's possible one of these weekends we'll make time for it. I would guess 2-5 weeks from now, looking at my current weekend schedule.

Unfortunately, getting slammed with duplicate notifications actually makes me feel sad about the whole prospect of doing open source in my spare time, so is likely to lengthen the time until a fix is available since it makes me avoid GitHub on the weekends.

If this is urgent for you, you can consider contracting me via email and we can discuss what kind of hourly consulting rate and payment plan would speed up the timeline for a fix. Until then, as I said, this is a spare time project and you should have no expectations of a quick fix.

**Comment by Hoshimikan6490** [comment]
Thank you for your reply.
I would like to have it fixed as soon as possible, but I understand that it is a spare-time project, so I will wait quietly until it is fixed. I'm sorry to mention you.

**Comment by sobstel** [comment]
I think it's already using npm punycode (not a core module) and this change fixes deprecation warnings: https://github.com/jsdom/tr46/commit/fef6e95243caaa0e46a1aa42fa21af6caef11e51

**Comment by domenic** [comment]
Yeah, I made time to test this issue and cannot reproduce any problems. `npm install` shows no problems and the following program does not produce any errors:

```js
require("tr46");
```

when using tr46 4.1.1.
