### ISSUE TITLE
The `punycode` module is deprecated.

### ISSUE THREAD

**Issue by LaKing** [jsdom/tr46#63]
(node:163221) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

[https://nodejs.org/api/punycode.html](https://nodejs.org/api/punycode.html)

https://www.npmjs.com/package/punycode

> Use require('punycode/') to import userland modules rather than core modules.

**Comment by domenic** [comment]
This module does not use the built-in punycode module and is not what's causing this error.

**Comment by NullVoxPopuli** [comment]
It used to though: https://github.com/jsdom/tr46/blob/v2.1.0/index.js#L3

so folks probably need to find what is using the old version of puny code and PR updates to those libraries.
(Or hope `overrides` doesn't break things)

**Comment by karcherm** [comment]
May I suggest a 3.0.1 release of `tr46` that just includes the missing slash in the `require` statement (i.e. cherry pick fef6e95243caaa0e46a1aa42fa21af6caef11e51), and otherwise is identical to 3.0.0? This would make a lot of dependency chains get rid of the deprecation warning.

**Comment by domenic** [comment]
Supporting more than one major version is something we're interested in spending maintainer bandwidth on.

**Comment by samstickland** [comment]
What is happening here.. This is the only possible library that could pull in punycode in our project:

```
npm list punycode
X
└─┬ jsdom@26.0.0
  └─┬ whatwg-url@14.1.1
    └─┬ tr46@5.0.0
      └── punycode@2.3.1
```

And we get this node warning: `(node:56362) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`

**Comment by samstickland** [comment]
Sorry for the noise, the deprecation is pointing to whatwg-url:

```
node --trace-deprecation mjml
(node:57992) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:114:7)
    at Function._load (node:internal/modules/cjs/loader:1100:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/sam/development/hubbado/hubbado_core/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
```

Which is odd, because they also import the userland module.. I'll go away now :)

**Comment by karcherm** [comment]
> What is happening here.. This is the only possible library that could pull in punycode in our project:

As you already found out, your issue is not directly related to tr46. Especially, it is not related to version 5.0.0 of tr46. Please see my answer on StackOverflow to this problem at https://stackoverflow.com/a/79371801 for more background information. Your trace is strange, as all variants of `whatwg-url` I can find that have the file `lib/url-state-machine.js` require tr46 in line 2. Please verify whether you also have an older version of whatwg-url (before 12.0.1) in your dependency tree that depends on tr46=3.0.0, which is a known offender regarding punycode.

**Comment by Wilfred** [comment]
Yikes, this is a really tricky thing to fix, and this issue ranks highly when searching google for punycode deprecation warnings.

(1) Node complains when you do `require('punycode')` because it refers to node's built-in punycode module instead of the external library from npm. It will complain regardless of whether the library has `punycode` in its listed dependencies or not.

(2) To fix this, the library needs `punycode` in its dependencies **and `require('punycode/')` to explicitly use the npm version**.

This is confusing because looking for `punycode` in your dependency tree isn't sufficient find the offending library.

(3) Typically this means that you have a version of tr46 before 4.0, either directly via a package that depends on it directly (whatwg-url before 12.0.1) or transitively (e.g. source-map before 0.75, node-fetch before 3.0).

(4) node 22 has disabled this deprecation warning for source code in node_modules, because it's really awkward to fix in your dependencies: https://github.com/nodejs/node/commit/fa49f0f7d5
